version: "3.3"

networks:
  gogs:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK}

services:

  mysql-gogs:
    restart: always
    build: ./images/mysql
    container_name: mysql-gogs
    hostname: mysql-gogs
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
    ports:
      - ${PORT_MYSQL}:3306
    expose:
      - ${PORT_MYSQL}
    volumes:
      - ./etc/mysql/data:/var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--default_authentication_plugin=mysql_native_password",
    ]
    networks:
      gogs:
        ipv4_address: ${NETWORK_MYSQL}

  gogs:
    restart: always
    build: ./images/gogs
    depends_on:
      - mysql-gogs
    links:
      - mysql-gogs:mysql
    ports:
      - ${PORT_GOGS_SSH}:22
      - ${PORT_GOGS}:3000
    volumes:
      - ./etc/gogs:/data/docker/gogs
    networks:
      gogs:
        ipv4_address: ${NETWORK_GOGS}
